//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Данные.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.СвойствоЗаказа = new HashSet<СвойствоЗаказа>();
            this.ИсторияЗаказа = new HashSet<ИсторияЗаказа>();
        }
    
        public int Ид { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
        public string ИмяКлиента { get; set; }
        public string ФамилияКлиента { get; set; }
        public string ОтчествоКлиента { get; set; }
        public string Телефон { get; set; }
        public string Почта { get; set; }
        public System.Guid ИдКлиента { get; set; }
        public System.Guid ИдСотрудника { get; set; }
        public System.DateTime ДатаИзменения { get; set; }
        public int ИдСтатуса { get; set; }
    
        public virtual СтатусЗаказа СтатусЗаказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СвойствоЗаказа> СвойствоЗаказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИсторияЗаказа> ИсторияЗаказа { get; set; }
    }
}
