//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Данные.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИсторияЗаказа
    {
        public int Ид { get; set; }
        public int ИдЗаказ { get; set; }
        public System.DateTime ДатаИзменения { get; set; }
        public System.Guid ИдСотрудника { get; set; }
        public string Коментарий { get; set; }
        public int СтатусИд { get; set; }
    
        public virtual Заказ Заказ { get; set; }
    }
}
