//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Данные.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отзыв
    {
        public int Ид { get; set; }
        public string Текст { get; set; }
        public bool Проверен { get; set; }
        public System.DateTime Дата { get; set; }
        public string Пользователь { get; set; }
        public System.Guid ПользовательИд { get; set; }
        public string Сущность { get; set; }
        public int СущностьИд { get; set; }
    }
}
