//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Данные.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class СвойствоЗаказа
    {
        public int Ид { get; set; }
        public string ИмяТовара { get; set; }
        public int ИдТовара { get; set; }
        public string ИмяПроизводителя { get; set; }
        public decimal Цена { get; set; }
        public Nullable<int> Скидка { get; set; }
        public int ИдЗаказа { get; set; }
        public int Количество { get; set; }
    
        public virtual Заказ Заказ { get; set; }
    }
}
