//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Данные.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public int Ид { get; set; }
        public string Имя { get; set; }
        public string Описание { get; set; }
        public string ИмяФайлаИзображения { get; set; }
        public int КатегорияИд { get; set; }
        public int ПроизводительИд { get; set; }
        public decimal Цена { get; set; }
        public Nullable<int> Скидка { get; set; }
    
        public virtual Категории Категории { get; set; }
        public virtual Производители Производители { get; set; }
    }
}
